name: bmrt_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  provider: ^6.1.1
  cloud_firestore: ^5.6.9
  google_fonts: ^6.1.0
  intl: ^0.20.2
  firebase_core_web: ^2.4.0
  flutter_carousel_widget: ^3.1.0
  carousel_slider: ^5.1.1
  logging: ^1.2.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  geolocator: ^14.0.1
  firebase_storage: ^12.4.7
  file_picker: ^10.1.9
  js: ^0.6.3
  share_plus: ^11.0.0
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^15.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/bmrt.png
    - assets/images/banner.jpeg
    - assets/images/banner2.jpeg
    - assets/images/banner3.jpeg
    - assets/images/gshock.jpg
    - assets/images/seiko.jpeg
    - assets/images/fossil.jpeg
    - assets/images/mk.jpg
    - assets/images/apple.jpeg
    - assets/images/tissot.jpeg
    - assets/images/timex.jpeg
    - assets/images/citizen.jpeg
    - assets/images/gshock_basic.jpeg
    - assets/images/edifice.jpg
    - assets/images/babyg.jpeg
    - assets/images/seiko2.jpeg
    - assets/images/timex_digital.jpg 