import 'package:bmrt_shop/services/product_service.dart';
import 'package:bmrt_shop/models/product.dart';
import 'package:uuid/uuid.dart';

class SeedData {
  static Future<void> addWatchProducts() async {
    final productService = ProductService();
    for (var productMap in products) {
      final product = Product(
        id: const Uuid().v4(),
        name: productMap['name'] as String,
        price: (productMap['price'] as num).toDouble(),
        image: productMap['image'] as String,
        rating: (productMap['rating'] as num).toDouble(),
        soldCount: productMap['soldCount'] as int,
        location: productMap['location'] as String,
        tags: List<String>.from(productMap['tags'] as List),
        discount: productMap['discount'] != null ? (productMap['discount'] as num).toDouble() : null,
        description: productMap['description'] as String,
      );
      await productService.addProduct(product);
    }
  }
}

final List<Map<String, dynamic>> products = [
  {
    'name': 'Seiko Presage Cocktail Time SRPB43',
    'price': 4500000,
    'image': 'assets/images/seiko.jpeg',
    'rating': 4.8,
    'soldCount': 1200,
    'location': 'Jakarta',
    'category': 'Jam Tangan Mewah',
    'description': 'Seiko Presage Cocktail Time SRPB43 dengan desain elegan terinspirasi dari koktail. Menggunakan mesin 4R35 dengan 24 batu, 23 jewels, dan power reserve 41 jam. Kaca Hardlex, case stainless steel 40.5mm, dan strap kulit asli.',
    'tags': ['Elegan', 'Koleksi', 'Automatic'],
    'discount': 0,
  },
  {
    'name': 'G-SHOCK GMW-B5000D-1',
    'price': 5845000,
    'image': 'assets/images/gshock.jpg',
    'rating': 4.5,
    'soldCount': 100,
    'location': 'Padang',
    'category': 'Jam Tangan Sport',
    'description': 'G-SHOCK GMW-B5000D-1 dengan case stainless steel full metal. Fitur Tough Solar, 200m water resistance, Multi Band 6, dan Bluetooth connectivity. Desain klasik dengan teknologi modern.',
    'tags': ['Sport', 'Tangguh', 'Digital'],
    'discount': 8,
  },
  {
    'name': 'Fossil Grant Chronograph FS5254',
    'price': 3200000,
    'image': 'assets/images/fossil.jpeg',
    'rating': 4.7,
    'soldCount': 1500,
    'location': 'Jakarta',
    'category': 'Jam Tangan Pria',
    'description': 'Fossil Grant Chronograph FS5254 dengan mesin quartz chronograph. Case stainless steel 44mm, kaca mineral, dan strap kulit asli. Desain klasik dengan 3 sub-dial chronograph.',
    'tags': ['Pria', 'Formal', 'Chronograph'],
    'discount': 0,
  },
  {
    'name': 'Michael Kors Runway MK6559',
    'price': 3800000,
    'image': 'assets/images/mk.jpg',
    'rating': 4.6,
    'soldCount': 950,
    'location': 'Jakarta',
    'category': 'Jam Tangan Wanita',
    'description': 'Michael Kors Runway MK6559 dengan case stainless steel 38mm dan bezel kristal. Mesin quartz, kaca mineral, dan strap stainless steel. Desain mewah dengan dial mother of pearl.',
    'tags': ['Wanita', 'Mewah', 'Luxury'],
    'discount': 0,
  },
  {
    'name': 'Apple Watch Series 8 GPS 45mm',
    'price': 5500000,
    'image': 'assets/images/apple.jpeg',
    'rating': 4.9,
    'soldCount': 2000,
    'location': 'Jakarta',
    'category': 'Jam Tangan Digital',
    'description': 'Apple Watch Series 8 GPS 45mm dengan fitur kesehatan canggih termasuk ECG, deteksi jatuh, dan monitoring suhu tubuh. Layar Always-On Retina, water resistant 50m, dan battery life hingga 18 jam.',
    'tags': ['Digital', 'Smartwatch', 'Fitness'],
    'discount': 0,
  },
  {
    'name': 'Tissot Classic Dream T109.407.11.031.00',
    'price': 4200000,
    'image': 'assets/images/tissot.jpeg',
    'rating': 4.7,
    'soldCount': 1100,
    'location': 'Jakarta',
    'category': 'Jam Tangan Mewah',
    'description': 'Tissot Classic Dream dengan mesin Swiss quartz. Case stainless steel 38mm, kaca sapphire, dan strap kulit asli. Desain minimalis dengan dial putih dan indeks Roman numerals.',
    'tags': ['Swiss', 'Premium', 'Classic'],
    'discount': 0,
  },
  {
    'name': 'Timex Weekender Chronograph TW2P72100',
    'price': 1200000,
    'image': 'assets/images/timex.jpeg',
    'rating': 4.5,
    'soldCount': 1800,
    'location': 'Jakarta',
    'category': 'Jam Tangan Pria',
    'description': 'Timex Weekender Chronograph dengan mesin quartz chronograph. Case 40mm, kaca mineral, dan strap NATO yang dapat diganti. Fitur Indiglo backlight dan water resistant 30m.',
    'tags': ['Kasual', 'Pria', 'Chronograph'],
    'discount': 0,
  },
  {
    'name': 'Citizen Eco-Drive BM6980-56E',
    'price': 3500000,
    'image': 'assets/images/citizen.jpeg',
    'rating': 4.8,
    'soldCount': 1300,
    'location': 'Jakarta',
    'category': 'Jam Tangan Sport',
    'description': 'Citizen Eco-Drive BM6980-56E dengan teknologi Eco-Drive yang menggunakan cahaya sebagai sumber energi. Case stainless steel 42mm, kaca mineral, dan water resistant 100m. Desain sporty dengan tachymeter bezel.',
    'tags': ['Eco', 'Sport', 'Solar'],
    'discount': 0,
  },
  {
    'name': 'G-SHOCK DW5600E-1V',
    'price': 2500000,
    'image': 'assets/images/gshock_basic.jpeg',
    'rating': 4.8,
    'soldCount': 1500,
    'location': 'Jakarta',
    'category': 'Jam Tangan Sport',
    'description': 'G-SHOCK DW5600E-1V, model klasik dengan ketahanan luar biasa. Fitur 200m water resistance, shock resistance, dan battery life 2 tahun. Desain ikonik yang telah menjadi standar G-SHOCK.',
    'tags': ['Tangguh', 'Sport', 'Digital'],
    'discount': 20,
  },
  {
    'name': 'Casio Edifice EFR-S108D-1AVUDF',
    'price': 3500000,
    'image': 'assets/images/edifice.jpg',
    'rating': 4.7,
    'soldCount': 800,
    'location': 'Jakarta',
    'category': 'Jam Tangan Mewah',
    'description': 'Casio Edifice EFR-S108D dengan mesin quartz chronograph. Case stainless steel 42mm, kaca mineral, dan bezel tachymeter. Desain sporty dengan sub-dial chronograph dan date display.',
    'tags': ['Mewah', 'Pria', 'Chronograph'],
    'discount': 15,
  },
  {
    'name': 'Baby-G BGA-240-7B',
    'price': 1800000,
    'image': 'assets/images/babyg.jpeg',
    'rating': 4.6,
    'soldCount': 600,
    'location': 'Jakarta',
    'category': 'Jam Tangan Wanita',
    'description': 'Baby-G BGA-240-7B dengan case putih 42.1mm. Fitur 100m water resistance, shock resistance, dan battery life 2 tahun. Desain fun dengan strap putih yang cocok untuk wanita aktif.',
    'tags': ['Wanita', 'Sport', 'Digital'],
    'discount': 10,
  },
  {
    'name': 'Seiko Presage Sharp Edge SPB165J1',
    'price': 4500000,
    'image': 'assets/images/seiko2.jpeg',
    'rating': 4.9,
    'soldCount': 400,
    'location': 'Jakarta',
    'category': 'Jam Tangan Mewah',
    'description': 'Seiko Presage Sharp Edge dengan mesin 6R35 automatic. Case stainless steel 39.3mm, kaca sapphire, dan dial pattern Asanoha. Power reserve 70 jam dan water resistant 100m.',
    'tags': ['Mewah', 'Pria', 'Automatic'],
    'discount': 0,
  },
  {
    'name': 'Timex Digital Classic T49963',
    'price': 1200000,
    'image': 'assets/images/timex_digital.jpg',
    'rating': 4.5,
    'soldCount': 300,
    'location': 'Jakarta',
    'category': 'Jam Tangan Digital',
    'description': 'Timex Digital Classic dengan tampilan digital retro. Fitur alarm, stopwatch, dan Indiglo backlight. Case 36mm, water resistant 30m, dan battery life 10 tahun.',
    'tags': ['Digital', 'Retro', 'Casual'],
    'discount': 5,
  },
];
