// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWkg1u6TqgS0rnoAylZONE1ODWzEcF7I8',
    appId: '1:234609322232:web:4988ab45943a9cd9bb730d',
    messagingSenderId: '234609322232',
    projectId: 'bmrtshop-b3bb5',
    authDomain: 'bmrtshop-b3bb5.firebaseapp.com',
    storageBucket: 'bmrtshop-b3bb5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWkg1u6TqgS0rnoAylZONE1ODWzEcF7I8',
    appId: '1:234609322232:android:4988ab45943a9cd9bb730d',
    messagingSenderId: '234609322232',
    projectId: 'bmrtshop-b3bb5',
    storageBucket: 'bmrtshop-b3bb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWkg1u6TqgS0rnoAylZONE1ODWzEcF7I8',
    appId: '1:234609322232:ios:4988ab45943a9cd9bb730d',
    messagingSenderId: '234609322232',
    projectId: 'bmrtshop-b3bb5',
    storageBucket: 'bmrtshop-b3bb5.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.bmrtShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWkg1u6TqgS0rnoAylZONE1ODWzEcF7I8',
    appId: '1:234609322232:macos:4988ab45943a9cd9bb730d',
    messagingSenderId: '234609322232',
    projectId: 'bmrtshop-b3bb5',
    storageBucket: 'bmrtshop-b3bb5.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.bmrtShop',
  );
}
